/*
 * Copyright (C) 2020 Samsung Electronics Co. LTD
 *
 * This software is proprietary of Samsung Electronics.
 * No part of this software, either material or conceptual may be copied or distributed, transmitted,
 * transcribed, stored in a retrieval system or translated into any human or computer language in any form by any means,
 * electronic, mechanical, manual or otherwise, or disclosed
 * to third parties without the express written permission of Samsung Electronics.
 */

#pragma once

#include <set>
#include <string>

#include "HalInterfaces.h"
using android::nn::V1_3::Model;

namespace graphgen {

/**
 * @brief GraphGen generate result type
 */
typedef enum {
    GRAPHGEN_SUCCESS = 0,
    GRAPHGEN_FAILED = 1,
    GRAPHGEN_TIMEOUT = 2,
    GRAPHGEN_UNSUPPORTED = 3
}GraphGenResult;

/**
 * @brief GraphGen State type
 */
typedef enum {
    GRAPHGEN_NORMAL = 0,
    GRAPHGEN_ERROR = 1
}GraphGenState;

/**
 * @brief NNC buffer struct
 * This is used to pass model data for EDEN Framework
 */
typedef struct {
    unsigned char *addr = 0;
    unsigned int size = 0;
}NNCBuffer;

/**
 * @brief Version for ENN
 * This is used to generate NNC for ENN
 * This Value will be deprecated after using UENN for all SoC
 */
typedef enum {
    V1 = 0,
    V2 = 1
}ENNVersion;

/**
 * @brief NNC Information
 * This is used to store whether nnc contain npu operator or dsp operator
 */
typedef struct {
    bool contain_npu_op = false;
    bool contain_dsp_op = false;
    ENNVersion schema_version = ENNVersion::V1;
}NNCInfo;

/**
 * @brief Device Information for On-device
 * This is used to query each devices whether operations of a model supporting or not.
 */
typedef enum {
    CPU_GPU = 0,
    NPU_DSP = 1
}GraphGenDev;

/**
 * @brief API interface class for GraphGen
 */
class GraphGen {
 public:
    /**
     * @brief Initial GraphGen and configure NPU on-device Compiler
     */
    GraphGen();

    /**
     * @brief Release all resources in GraphGen and NPU on-device Compiler
     */
    ~GraphGen();

    /**
     * @brief A function to check soc name whether is supported by GraphGen
     * @param soc_name The name of soc is provide by ENN Driver, 1000, 990, 9830, 980, 9630 etc.
     * @return True if GraphGen supported soc, otherwise False
     */
    bool isSupportedSoC(int32_t soc_name);

    /**
     * @brief A function to check ANN Model whether is supported by GraphGen.
     * @param model a ANN model is provided by ENN Driver
     * @return True if GraphGen support ANN model, otherwise False
     */
    bool isSupportedANNModel(const Model& model);

    /**
     * @brief A function to generate a nnc model for GPU/NPU/DSP
     * @param model A ANN model is provided by ENN Driver
     * @param device primary target device for model to bind on.
     * @param soc_name The name of soc is provide by ENN Driver, 1000, 990, 9830, 980, 9630 etc.
     * @param nnc_buffer A model buffer for EDEN framework
     * @param nnc_info The information about NNC model
     * @return GraphGenResult
     */
    GraphGenResult generate(const Model& model,
                            const GraphGenDev device, const int32_t soc_name,
                            NNCBuffer* nnc_buffer, NNCInfo* nnc_info);

    /**
     * @brief A function to free the memory which nnc_buffer_ptr point
     * @param nnc_buffer_ptr A point to point the nnc buffer which is generated by GraphGen
     */
    void freeMemory(NNCBuffer* nnc_buffer);

    /**
     * @brief A fucntion to return the state of GraphGen
     * @return GraphGenState
     */
    GraphGenState getStatus();


 private:
    std::set<unsigned char*> nnc_buffers_addr;
    std::vector<bool> NPU_supported_ops;
    std::vector<bool> DSP_supported_ops;
    std::vector<bool> GPU_supported_ops;
    bool supporeted_by_npu_dsp = false;
};

}  // namespace graphgen
