/*
 * Copyright (C) 2019 Samsung Electronics Co. LTD
 *
 * This software is proprietary of Samsung Electronics.
 * No part of this software, either material or conceptual may be copied or distributed, transmitted,
 * transcribed, stored in a retrieval system or translated into any human or computer language in any form by any means,
 * electronic, mechanical, manual or otherwise, or disclosed
 * to third parties without the express written permission of Samsung Electronics.
 */

/**
 * @file    EdenPreparedModel.cpp
 * @brief   This is EdenPreparedModel class file.
 * @details This header implements IPreparedModel interface.
 * @author  minsu.jeon (minsu.jeon@samsung.com)
 */

#include <iostream>
#include <sys/mman.h>  // munmap

#include "log.h"

#include "ExecutionBurstServer.h"  // ExecutionBurstServer
#include "ValidateHal.h"           // validateRequest
#include "Utils.h"                 // convertToV1_0, convertToV1_1, android::nn::initVLogMask, logModelToInfo, DRIVER

#include "EdenPreparedModel.h"
#include "NNAgent.h"               // NNAgent
#include "EdenModelConvertLib.h"   // loadAndroidModelInputToEdenOperation

#ifdef LOG_TAG
#undef LOG_TAG
#endif
#define LOG_TAG "EdenDriver::EdenPreparedModel"

using ::android::hardware::neuralnetworks::V1_0::RequestArgument;

namespace android {
namespace nn {
namespace eden_driver {

static const V1_2::Timing kNoTiming = {.timeOnDevice = UINT64_MAX, .timeInDriver = UINT64_MAX};

class DriverExecutionCallback_1_2 : public V1_2::IExecutionCallback {
 public:
    DriverExecutionCallback_1_2(executeSynchronously_cb cb) : myCb(cb) {
    }

    Return<void> notify(V1_0::ErrorStatus /*status*/) {
        return Void();
    }

    Return<void> notify_1_2(V1_0::ErrorStatus status, const hidl_vec<V1_2::OutputShape>& outputShapes, const V1_2::Timing& timing) {
        myCb(status, outputShapes, timing);
        return Void();
    }

    executeSynchronously_cb myCb;
};

class DriverExecutionCallback_1_3 : public V1_3::IExecutionCallback {
 public:
    DriverExecutionCallback_1_3(executeSynchronously_1_3_cb cb) : myCb(cb) {
    }

    Return<void> notify(V1_0::ErrorStatus /*status*/) {
        return Void();
    }

    Return<void> notify_1_2(V1_0::ErrorStatus /*status*/, const hidl_vec<V1_2::OutputShape>& /*outputShapes*/, const V1_2::Timing& /*timing*/) {
        return Void();
    }

    Return<void> notify_1_3(V1_3::ErrorStatus status, const hidl_vec<V1_2::OutputShape>& outputShapes, const V1_2::Timing& timing) {
        myCb(status, outputShapes, timing);
        return Void();
    }

    executeSynchronously_1_3_cb myCb;
};

/**
 * @brief EdenPreparedModel constructor
 * @details This function keeps all related information for a given model internally.
 * @param[in] nnAgent instance of NNAgent
 * @param[in] model Android NN Model
 * @param[in] modelId unique model id generated by Eden Runtime service
 * @param[in] edenModel EdenModel
 * @param[in] inputBuffers InHouseBufferInfo representing for buffer information returned by Eden Runtime service
 * @param[in] outputBuffers InHouseBufferInfo representing for buffer information returned by Eden Runtime service
 * @param[in] vecAddr virtual address for buffers on pools
 * @param[in] vecSize size for buffers on pools
 * @param[in] operandValues copied internal operandValues of model
 * @param[in] mapOperandIdFromAToE map operand id from Android NN Model to Eden Model
 * @param[in] mapOperationIdFromAToE map operation id from Android NN Model to Eden Model
 * @param[in] inputConsumers android operation id that consumes an operand at index
 * @param[in] internalBuffers internal buffers allocated for this model
 * @param[in] vecIMemoryOnAshmems list of sp<IMemory> that returned via mapMemory()
 * @returns return code
 */
EdenPreparedModel::EdenPreparedModel(NNAgent* nnAgent,
                                     const V1_3::Model& model, uint32_t modelId, EdenModel* edenModel,
                                     HwPreference hwPreference, NNCBuf nncBuffer, bool isNNCModel,
                                     void* inputAddr, int32_t inputNumOfBuffers,
                                     void* outputAddr, int32_t outputNumOfBuffers,
                                     std::vector<char*>& vecMappedAddr, std::vector<int32_t>& vecMappedSize,
                                     std::unique_ptr<uint8_t[]>& operandValues,
                                     std::map<int32_t, int32_t>& mapOperandIdFromAToE,
                                     std::map<int32_t, int32_t>& mapOperationIdFromAToE,
                                     std::vector<int32_t>& inputConsumers,
                                     std::vector<std::unique_ptr<int32_t[]>>& internalBuffers,
                                     std::vector<sp<IMemory>>& vecIMemoryOnAshmems) :
    model(model),
    modelId(modelId),
    hwPreference(hwPreference),
    inputAddr(inputAddr), inputNumOfBuffers(inputNumOfBuffers),
    outputAddr(outputAddr), outputNumOfBuffers(outputNumOfBuffers),
    nnAgent_(nnAgent), edenModel_(edenModel),
    nncBuffer_(nncBuffer), isNNCModel_(isNNCModel) {
    LOGD(EDEN_DRIVER, "%s(+)\n", __func__);
    LOGD(EDEN_DRIVER, "modelId: %u, inputAddr: %p, inputNumOfBuffers: %d, outputAddr: %p, outputNumOfBuffers: %d is created!\n",
                       modelId, inputAddr, inputNumOfBuffers, outputAddr, outputNumOfBuffers);

    updatedOperations.resize(0);

    vecMappedAddr_ = vecMappedAddr;
    vecMappedSize_ = vecMappedSize;

    operandValues_ = std::move(operandValues);

    mapOperandIdFromAToE_ = mapOperandIdFromAToE;
    mapOperationIdFromAToE_ = mapOperationIdFromAToE;
    inputConsumers_ = inputConsumers;

    for (auto& buffers : internalBuffers) {
        internalBuffers_.push_back(std::move(buffers));
    }

    vecIMemoryOnAshmems_ = vecIMemoryOnAshmems;

    needInputBuffers_ = (inputAddr == nullptr ? true : false);
    needOutputBuffers_ = (outputAddr == nullptr ? true : false);

    LOGD(EDEN_DRIVER, "%s(-)\n", __func__);
}

/**
 * @brief EdenPreparedModel destructor
 * @details This function releases all related information for a given model internally.
 * @returns
 */
EdenPreparedModel::~EdenPreparedModel() {
    LOGD(EDEN_DRIVER, "%s(+)\n", __func__);
    // Unmap
    LOGD(EDEN_DRIVER, "Unmap on virtual address...\n");
    for (size_t idx = 0; idx < vecMappedAddr_.size(); idx++) {
        char* mappedAddr = static_cast<char*>(vecMappedAddr_.at(idx));
        delete[] mappedAddr;
    }
    LOGD(EDEN_DRIVER, "Unmap on virtual address...Done!\n");

    if (nnAgent_) {
        nnAgent_->closeModel(modelId, nncBuffer_, isNNCModel_);
    }
    LOGD(EDEN_DRIVER, "%s(-)\n", __func__);
}

static V1_3::ErrorStatus retCodeToErrorStatus(int32_t retCode) {
    V1_3::ErrorStatus errorStatus = V1_3::ErrorStatus::NONE;
    switch (retCode) {
        case INVALID_PARAMS:
            errorStatus = V1_3::ErrorStatus::INVALID_ARGUMENT;
            break;
        default:
            errorStatus = V1_3::ErrorStatus::GENERAL_FAILURE;
            break;
    }
    return errorStatus;
}

static void callNotifyWithError(const sp<V1_0::IExecutionCallback>& callback_1_0, V1_3::ErrorStatus status) {
    callback_1_0->notify(convertToV1_0(status));
}

static void callNotifyWithError(const sp<V1_2::IExecutionCallback>& callback_1_2, V1_3::ErrorStatus status) {
    callback_1_2->notify_1_2(convertToV1_0(status), {}, kNoTiming);
}

static void callNotifyWithError(const sp<V1_3::IExecutionCallback>& callback_1_3, V1_3::ErrorStatus status) {
    callback_1_3->notify_1_3(status, {}, kNoTiming);
}

template <typename T_Request, typename T_Callback>
static Return<V1_3::ErrorStatus> executeBaseOnEdenPreparedModel(EdenPreparedModel* edenPreparedModel,
                                                                          NNAgent* nnAgent,
                                                                          const T_Request& request,
                                                                          V1_2::MeasureTiming measure,
                                                                          const V1_3::OptionalTimePoint& /*deadline*/,
                                                                          const V1_3::OptionalTimeoutDuration& /*loopTimeoutDuration*/,
                                                                          const T_Callback& callback) {
    LOGD(EDEN_DRIVER, "%s(+)\n", __func__);

    if (callback.get() == nullptr) {
        LOGE(EDEN_DRIVER, "Error, invalid callback passed to execute\n");
        return V1_3::ErrorStatus::INVALID_ARGUMENT;
    }

    if (!validateRequest(convertToV1_3(request), edenPreparedModel->model)) {
        callNotifyWithError(callback, V1_3::ErrorStatus::INVALID_ARGUMENT);
        return V1_3::ErrorStatus::INVALID_ARGUMENT;
    }

    if (!verifyDimension(convertToV1_3(request), edenPreparedModel->model)) {
        callNotifyWithError(callback, V1_3::ErrorStatus::INVALID_ARGUMENT);
        return V1_3::ErrorStatus::INVALID_ARGUMENT;
    }

    //show();
    //showRequest(request);

    // Load input data(Android NN Memory) to input buffer(Eden Memory Manager)
    // loadInputData(request);

    // Execute
    int32_t ret = nnAgent->execute(edenPreparedModel, convertToV1_3(request), measure, callback);
    if (ret != RET_OK) {
        V1_3::ErrorStatus errorStatus = retCodeToErrorStatus(ret);
        callNotifyWithError(callback, errorStatus);
        LOGE(EDEN_DRIVER, "%s(-)\n", __func__);
        return errorStatus;
    }

    LOGD(EDEN_DRIVER, "%s(-)\n", __func__);
    return V1_3::ErrorStatus::NONE;
}

template <typename T_Request, typename T_Callback>
static Return<void> executeSynchronouslyBaseOnEdenPreparedModel(EdenPreparedModel* edenPreparedModel,
                                                                     NNAgent* nnAgent,
                                                                     const T_Request& request,
                                                                     V1_2::MeasureTiming measure,
                                                                     const V1_3::OptionalTimePoint& /*deadline*/,
                                                                     const V1_3::OptionalTimeoutDuration& /*loopTimeoutDuration*/,
                                                                     const T_Callback& callback) {
    LOGD(EDEN_DRIVER, "%s(+)\n", __func__);

    if (!validateRequest(convertToV1_3(request), edenPreparedModel->model)) {
        callNotifyWithError(callback, V1_3::ErrorStatus::INVALID_ARGUMENT);
        return Void();
    }

    if (!verifyActivation(edenPreparedModel->model)) {
        callNotifyWithError(callback, V1_3::ErrorStatus::INVALID_ARGUMENT);
        return Void();
    }

    if (!verifyDimension(convertToV1_3(request), edenPreparedModel->model)) {
        callNotifyWithError(callback, V1_3::ErrorStatus::INVALID_ARGUMENT);
        return Void();
    }

    // Execute
    int32_t ret = nnAgent->executeSynchronously(edenPreparedModel, convertToV1_3(request),
                                                measure, callback);
    if (ret != RET_OK) {
        V1_3::ErrorStatus errorStatus = retCodeToErrorStatus(ret);
        callNotifyWithError(callback, errorStatus);
        LOGE(EDEN_DRIVER, "%s(-)\n", __func__);
        return Void();
    }

    LOGD(EDEN_DRIVER, "%s(-)\n", __func__);
    return Void();
}

/**
 * @brief execute a given Request
 * @details This function executes a given Request. Once it is complete, result is notified via callback.
 * @param[in] request Request
 * @param[in] callback callback to be executed
 * @returns return code
 */
Return<V1_0::ErrorStatus> EdenPreparedModel::execute(const V1_0::Request& request,
                                                               const sp<V1_0::IExecutionCallback>& callback_1_0) {
    return convertToV1_0(executeBaseOnEdenPreparedModel(this, this->nnAgent_, request, V1_2::MeasureTiming::NO, {}, {}, callback_1_0));
}

Return<V1_0::ErrorStatus> EdenPreparedModel::execute_1_2(const V1_0::Request& request,
                                                                   V1_2::MeasureTiming measure,
                                                                   const sp<V1_2::IExecutionCallback>& callback_1_2) {
    return convertToV1_0(executeBaseOnEdenPreparedModel(this, this->nnAgent_, request, measure, {}, {}, callback_1_2));
}

Return<V1_3::ErrorStatus> EdenPreparedModel::execute_1_3(const V1_3::Request& request,
                                                                   V1_2::MeasureTiming measure,
                                                                   const V1_3::OptionalTimePoint& deadline,
                                                                   const V1_3::OptionalTimeoutDuration& loopTimeoutDuration,
                                                                   const sp<V1_3::IExecutionCallback>& callback_1_3) {
    return executeBaseOnEdenPreparedModel(this, this->nnAgent_, request, measure, deadline,
                                                                loopTimeoutDuration, callback_1_3);
}

Return<void> EdenPreparedModel::executeSynchronously(const V1_0::Request& request,
                                                          V1_2::MeasureTiming measure,
                                                          executeSynchronously_cb cb) {
    sp<V1_2::IExecutionCallback> callback = new DriverExecutionCallback_1_2(cb);
    return executeSynchronouslyBaseOnEdenPreparedModel(this, this->nnAgent_, request, measure, {}, {}, callback);
}

Return<void> EdenPreparedModel::executeSynchronously_1_3(const V1_3::Request& request,
                                                              V1_2::MeasureTiming measure,
                                                              const V1_3::OptionalTimePoint& deadline,
                                                              const V1_3::OptionalTimeoutDuration& loopTimeoutDuration,
                                                              executeSynchronously_1_3_cb cb) {
    sp<V1_3::IExecutionCallback> callback = new DriverExecutionCallback_1_3(cb);
    return executeSynchronouslyBaseOnEdenPreparedModel(this, this->nnAgent_, request, measure, deadline, loopTimeoutDuration, callback);
}

Return<void> EdenPreparedModel::configureExecutionBurst(const sp<V1_2::IBurstCallback>& callback,
                                                        const MQDescriptorSync<V1_2::FmqRequestDatum>& requestChannel,
                                                        const MQDescriptorSync<V1_2::FmqResultDatum>& resultChannel,
                                                        configureExecutionBurst_cb cb) {
    LOGD(EDEN_DRIVER, "%s(+)\n", __func__);

    const sp<V1_2::IBurstContext> burst =
            ExecutionBurstServer::create(callback, requestChannel, resultChannel, this);

    if (burst == nullptr) {
        LOGE(EDEN_DRIVER, "burst is null!");
        cb(V1_0::ErrorStatus::GENERAL_FAILURE, {});
    } else {
        cb(V1_0::ErrorStatus::NONE, burst);
    }

    LOGD(EDEN_DRIVER, "%s(-)\n", __func__);
    return Void();
}

Return<void> EdenPreparedModel::executeFenced(const V1_3::Request& request,
                                                   const hidl_vec<hidl_handle>& waitFor,
                                                   V1_2::MeasureTiming measure,
                                                   const V1_3::OptionalTimePoint& /*deadline*/,
                                                   const V1_3::OptionalTimeoutDuration& /*loopTimeoutDuration*/,
                                                   const V1_3::OptionalTimeoutDuration& /*duration*/,
                                                   executeFenced_cb cb) {
    LOGD(EDEN_DRIVER, "%s(+)\n", __func__);

    if (!validateRequest(request, model)) {
        cb(V1_3::ErrorStatus::INVALID_ARGUMENT, hidl_handle(nullptr), nullptr);
        LOGW(EDEN_DRIVER, "%s(-) INVALID request\n", __func__);
        return Void();
    }

    // Wait for the dependent events to signal
    for (const auto& fenceHandle : waitFor) {
        if (!fenceHandle.getNativeHandle()) {
            cb(V1_3::ErrorStatus::INVALID_ARGUMENT, hidl_handle(nullptr), nullptr);
            return Void();
        }
        int syncFenceFd = fenceHandle.getNativeHandle()->data[0];
        if (syncWait(syncFenceFd, -1) != FenceState::SIGNALED) {
            LOG(ERROR) << "syncWait failed";
            cb(V1_3::ErrorStatus::GENERAL_FAILURE, hidl_handle(nullptr), nullptr);
            return Void();
        }
    }

    if (!verifyDimension(request, model)) {
        cb(V1_3::ErrorStatus::INVALID_ARGUMENT, hidl_handle(nullptr), nullptr);
        return Void();
    }

    // Execute
    int32_t ret = nnAgent_->executeFenced(this, request, waitFor, measure, cb);
    if (ret != RET_OK) {
        V1_3::ErrorStatus errorStatus = retCodeToErrorStatus(ret);
        cb(errorStatus, hidl_handle(nullptr), nullptr);
        LOGE(EDEN_DRIVER, "%s(-)\n", __func__);
        return Void();
    }

    LOGD(EDEN_DRIVER, "%s(-)\n", __func__);
    return Void();
}

/**
 * @brief load input data on request and copy them to EdenBuffers for inputs
 * @details This function loads a buffers on request and copy them to EdenBuffers for inputs.
 *          EdenBuffers should be allocated before.
 *          If inputs[idx].hasNoValue==1, it loads 1)default values or 2)set size to 0.
 * @param[in] request Request
 * @returns return code
 */
int32_t EdenPreparedModel::loadInputData(const V1_3::Request& request, BufferInfoOnExecute& bufInfoOnExecute) {
    LOGD(EDEN_DRIVER, "%s(+)\n", __func__);

    const std::vector<RequestArgument>& inputs = request.inputs;

    for (size_t idx = 0; idx < inputs.size(); idx++) {
        const RequestArgument &inputArgs = inputs[idx];
        if (inputArgs.hasNoValue) {
            LOGD(EDEN_DRIVER, "inputs[%zu].hasNoValue == 1, check if there is any default values for it.\n", idx);;
            loadDefaultDataOnTargetBuffer(idx);
            continue;
        }

        // Get virtual address of input data at #idx
        int32_t poolIndex = inputArgs.location.poolIndex;
        int32_t offset = inputArgs.location.offset;
        int32_t length = inputArgs.location.length;

        LOGD(EDEN_DRIVER, "inputIndex= [%zu], poolIndex = [%d]\n", idx, poolIndex);
        switch (request.pools[poolIndex].getDiscriminator()) {
            case V1_3::Request::MemoryPool::hidl_discriminator::hidlMemory: {
                char* virtAddr = nullptr;
                int32_t ret = bufInfoOnExecute.loadHidlMem(request.pools[poolIndex].hidlMemory(), true, virtAddr);
                if (ret != RET_OK) {
                    LOGE(EDEN_DRIVER, "%s(-) Fail on getVirtualAddressOnPool!\n", __func__);
                    return ret;
                }

                ret = loadDataOnTargetBuffer(virtAddr + offset, length, idx);
                if (ret != RET_OK) {
                    LOGE(EDEN_DRIVER, "%s(-) Fail on loadDataOnTargetBuffer!\n", __func__);
                    return ret;
                }
            }
            break;
            case V1_3::Request::MemoryPool::hidl_discriminator::token:
            break;
        }
    }
    LOGD(EDEN_DRIVER, "%s(-)\n", __func__);
    return 0;
}

/**
 * @brief load output data on EdenBuffers for outputs and copy them to output buffers on request
 * @details This function loads a buffers on EdenBuffers for outputs and copy them to output buffers on request.
 *          EdenBuffers should be allocated before.
 * @param[in] request Request
 * @returns return code
 */
int32_t EdenPreparedModel::loadOutputData(const V1_3::Request& request, BufferInfoOnExecute& bufInfoOnExecute) {
    LOGD(EDEN_DRIVER, "%s(+)\n", __func__);

    const std::vector<RequestArgument>& outputs = request.outputs;

    EdenBuffer* edenBufferForOutputs = reinterpret_cast<EdenBuffer*>(outputAddr);

    for (size_t idx = 0; idx < outputs.size(); idx++) {
        const RequestArgument& outputArgs = outputs[idx];
        if (outputArgs.hasNoValue) {
            continue;
        }

        EdenBuffer* outputBufferAddr = &(edenBufferForOutputs[idx]);
        LOGD(EDEN_DRIVER, "outputBufferAddr addr:%p, size=%d\n", outputBufferAddr->addr, outputBufferAddr->size);

        int32_t poolIndex = outputArgs.location.poolIndex;
        int32_t offset = outputArgs.location.offset;
        int32_t length = outputArgs.location.length;

        switch (request.pools[poolIndex].getDiscriminator()) {
            case V1_3::Request::MemoryPool::hidl_discriminator::hidlMemory : {
                char* virtAddr = nullptr;
                int32_t ret = bufInfoOnExecute.loadHidlMem(request.pools[poolIndex].hidlMemory(), false, virtAddr);
                if (ret != RET_OK) {
                    LOGE(EDEN_DRIVER, "%s(-) Fail on getVirtualAddressOnPool!\n", __func__);
                    return ret;
                }

                LOGD(EDEN_DRIVER, "Load from %p to %p, length=%d\n", outputBufferAddr->addr,
                                                        reinterpret_cast<void*>(virtAddr + offset), length);
                bufInfoOnExecute.startUpdate(virtAddr);
                std::memcpy(reinterpret_cast<void*>(virtAddr + offset), outputBufferAddr->addr, length);
                bufInfoOnExecute.endUpdate(virtAddr);
            }
            break;

            case V1_3::Request::MemoryPool::hidl_discriminator::token:
            break;
        }
    }
    LOGD(EDEN_DRIVER, "%s(-)\n", __func__);
    return 0;
}

int32_t EdenPreparedModel::resolveUnknownDimensions(const V1_3::Request& request) {
    if (isNNCModel_) {
        // on-device GraphGen can't support UnknownDimensions scenario.
        // If the PreparedModel is NNC model, it means it is not UnknownDimensions case.
        return RET_OK;
    }
    // Resolve input buffer allocation
    bool resolved = true;
    if (needInputBuffers_) {
        // It means input buffer allocation was not executed at preparedModel,
        // which means dimensions for input buffers were unknown at preparedModel.

        const std::vector<RequestArgument>& inputs = request.inputs;

        for (size_t inputIdx = 0; inputIdx < inputs.size(); inputIdx++) {
            const RequestArgument& inputArgs = inputs[inputIdx];
            if (inputArgs.hasNoValue) {
                LOGD(EDEN_DRIVER, "inputs[%zu].hasNoValue == 1, skip it.\n", inputIdx);
                continue;
            }

            // Get android operand id used as model input
            int32_t androidOperandIdx = model.main.inputIndexes[inputIdx];
            auto iter = mapOperandIdFromAToE_.find(androidOperandIdx);
            if (iter != mapOperandIdFromAToE_.end()) {
                LOGD(EDEN_DRIVER, "inputIndexes[%zu] is converted to EdenOperand, id=[%d]\n",
                                   inputIdx, iter->second);
                int32_t edenOperandIdx = iter->second;

                // Get dimensions
                size_t rank = inputArgs.dimensions.size();
                static int32_t newDims[4];
                for (size_t idx = 0; idx < rank; idx++) {
                    newDims[idx] = inputArgs.dimensions[idx];
                }
                for (size_t idx = rank; idx < 4; idx++) {
                    newDims[idx] = 1;
                }

                // Update dimensions of edenOperand on edenModel
                if (rank == 0) {
                    LOGD(EDEN_DRIVER, "edenOperandIdx(%d)'s rank is zero...\n", edenOperandIdx);
                    resolved = false;
                } else {
                    edenModel_->UpdateOperandDimensions(edenOperandIdx, rank, newDims);
                }
            } else {
                LOGD(EDEN_DRIVER, "No matched edenOperand... skip it\n");
                continue;
            }
        }

        if (resolved) {
            needInputBuffers_ = false;
        }
    }

    // Resolve output buffer allocation
    resolved = true;
    if (needOutputBuffers_) {
        // It means output buffer allocation was not executed at preparedModel,
        // which means dimensions for output buffers were unknown at preparedModel.

        const std::vector<RequestArgument>& outputs = request.outputs;

        for (size_t outputIdx = 0; outputIdx < outputs.size(); outputIdx++) {
            const RequestArgument& outputArgs = outputs[outputIdx];

             // Get android operand id used as model output
            int32_t androidOperandIdx = model.main.outputIndexes[outputIdx];
            auto iter = mapOperandIdFromAToE_.find(androidOperandIdx);
            if (iter != mapOperandIdFromAToE_.end()) {
                LOGD(EDEN_DRIVER, "outputIndexes[%zu] is converted to EdenOperand, id=[%d]\n",
                                   outputIdx, iter->second);
                int32_t edenOperandIdx = iter->second;

                bool unknown = false;
                uint32_t rank = static_cast<uint32_t>(outputArgs.dimensions.size());

                // Check unknown rank, unknown dimension
                if (rank == 0) {
                    unknown = true;
                } else {
                    for (uint32_t idx = 0; idx < rank; idx++) {
                        if (outputArgs.dimensions[idx] == 0) {
                            unknown = true;
                            break;
                        }
                    }
                }

                if (unknown) {
                    // Need to deduce output size
                    bool ret = edenModel_->DeduceOperandDimensions(edenOperandIdx);
                    if (ret == false) {
                        resolved = false;
                        break;
                    }
                } else {
                    // Get dimensions
                    static int32_t newDims[4];
                    for (uint32_t idx = 0; idx < rank; idx++) {
                        newDims[idx] = outputArgs.dimensions[idx];
                    }
                    for (uint32_t idx = rank; idx < 4; idx++) {
                        newDims[idx] = 1;
                    }

                    // Update dimensions of edenOperand on edenModel
                    edenModel_->UpdateOperandDimensions(edenOperandIdx, static_cast<int32_t>(rank), newDims);
                }
            } else {
                LOGD(EDEN_DRIVER, "No matched edenOperand... skip it\n");
                continue;
            }
        }

        if (resolved) {
            needOutputBuffers_ = false;
        }
    }

    return RET_OK;
}

void EdenPreparedModel::updateInputBuffers(void* addr, int32_t numOfBuffers) {
    inputAddr = addr;
    inputNumOfBuffers = numOfBuffers;
    if (inputAddr) needInputBuffers_ = false;
}

void EdenPreparedModel::updateOutputBuffers(void* addr, int32_t numOfBuffers) {
    outputAddr = addr;
    outputNumOfBuffers = numOfBuffers;
    if (outputAddr) needOutputBuffers_ = false;
}

bool EdenPreparedModel::readyToAllocateInputBuffers(const V1_3::Request* request) {
    const std::vector<RequestArgument>& inputs = request->inputs;

    for (size_t inputIdx = 0; inputIdx < inputs.size(); inputIdx++) {
        // Get android operand id used as model input
        int32_t androidOperandIdx = model.main.inputIndexes[inputIdx];
        auto iter = mapOperandIdFromAToE_.find(androidOperandIdx);
        if (iter != mapOperandIdFromAToE_.end()) {
            LOGD(EDEN_DRIVER, "inputIndexes[%zu] is converted to EdenOperand, id=[%d]\n",
                               inputIdx, iter->second);
            int32_t edenOperandIdx = iter->second;
            const RequestArgument& inputArgs = inputs[inputIdx];
            if (inputArgs.hasNoValue) {
                LOGD(EDEN_DRIVER, "inputs[%zu].hasNoValue == 1, skip it.\n", inputIdx);
            } else {
                if (edenModel_->ReadyToAllocateInputBuffers(&edenOperandIdx) == false) {
                    return false;
                }
            }
        }
    }

    return true;
}

bool EdenPreparedModel::readyToAllocateOutputBuffers(const V1_3::Request* request) {
    const std::vector<RequestArgument>& outputs = request->outputs;

    for (size_t outputIdx = 0; outputIdx < outputs.size(); outputIdx++) {
        // Get android operand id used as model output
        int32_t androidOperandIdx = model.main.outputIndexes[outputIdx];
        auto iter = mapOperandIdFromAToE_.find(androidOperandIdx);
        if (iter != mapOperandIdFromAToE_.end()) {
            LOGD(EDEN_DRIVER, "outputIndexes[%zu] is converted to EdenOperand, id=[%d]\n",
                               outputIdx, iter->second);
            int32_t edenOperandIdx = iter->second;
            const RequestArgument& outputArgs = outputs[outputIdx];
            if (outputArgs.hasNoValue) {
                LOGD(EDEN_DRIVER, "outputs[%zu].hasNoValue == 1, skip it.\n", outputIdx);
            } else {
                if (edenModel_->ReadyToAllocateOutputBuffers(&edenOperandIdx) == false) {
                    return false;
                }
            }
        }
    }

    return true;
}

/**
 * @brief load default values to a target buffer matched to a given input index
 * @details This function loads a default value to a target buffers.
 *          Target buffer is determined based on a given input index.
 *          If there is a target buffer, it loads a default value.
 *          If it is translated as an option, it loads that field on option.
 * @param[in] inputIdx input index on request.inputs
 * @returns return code
 */
int32_t EdenPreparedModel::loadDefaultDataOnTargetBuffer(int32_t inputIdx) {
    LOGD(EDEN_DRIVER, "%s(+)\n", __func__);

    // Get android operand id used as model input
    int32_t androidOperandIdx = model.main.inputIndexes[inputIdx];

    // Which operation uses this operand id as input?

    // Case 1. There is matched edenOperand. That means memcpy is enough.
    bool exist = false;
    if (isNNCModel_) {
        exist = true;
    } else {
        auto iter = mapOperandIdFromAToE_.find(androidOperandIdx);
        if (iter != mapOperandIdFromAToE_.end()) {
            exist = true;
            LOGD(EDEN_DRIVER, "inputIndexes[%d] is converted to EdenOperand, id=[%d]\n", inputIdx, iter->second);
        }
    }

    // 1. Who is the consumer for this input operand?
    int32_t androidOperationIdx = inputConsumers_.at(inputIdx);
    const V1_3::Operation& androidOperation = model.main.operations[androidOperationIdx];

    // 2. Find index number matched to a given androidOperandIdx
    int32_t indexNumber = 0;
    for (size_t idx = 0; idx < androidOperation.inputs.size(); idx++) {
        if (static_cast<int32_t>(androidOperation.inputs[idx]) == androidOperandIdx) {
            indexNumber = idx;
            break;
        }
    }
    LOGD(EDEN_DRIVER, "androidOperandIdx=[%d] is %dth index!\n", androidOperandIdx, indexNumber);

    if (exist) {  // To be loaded on input buffers
        // @todo Currently, input buffer order and input indexes has same order.
        EdenBuffer* edenBufferForInputs = reinterpret_cast<EdenBuffer*>(inputAddr);
        EdenBuffer* inputBufferAddr = &(edenBufferForInputs[inputIdx]);
        LOGD(EDEN_DRIVER, "inputBufferAddr addr:%p, size=%d\n", inputBufferAddr->addr, inputBufferAddr->size);
        void* targetAddr = inputBufferAddr->addr;
        int32_t targetSize = inputBufferAddr->size;

        LOGD(EDEN_DRIVER, "targetAddr=%p, targetSize=%d\n", targetAddr, targetSize);

        bool loaded = loadDefaultValuesForOptionalInputs(model, indexNumber, androidOperation, static_cast<char*>(targetAddr), targetSize);
        if (loaded == false) {
            // There is no loaded default values on buffer.
            // In this case, it contains invalid values.
            // To avoid use this invalid values by consumers,
            // forcely set buffer size to 0 to indicate there is no valid data on this buffer.
            LOGD(EDEN_DRIVER, "There is no loaded default value on buffer=%p, Forcely set buffer size=0\n", targetAddr);
            inputBufferAddr->size = 0;
        }
    } else {  // To be loaded on a specific position
        // 3. Find edenOperation matched to a given androidOperationIdx
        int32_t edenOperationIdx = mapOperationIdFromAToE_[androidOperationIdx];
        EdenOperation* edenOperation = getEdenOperation(edenModel_, edenOperationIdx);

        // 3.1 Keep updated operations
        updatedOperations.push_back(edenOperationIdx);
        LOGD(EDEN_DRIVER, "push %d, numOfOperations=%d\n", edenOperationIdx, static_cast<int32_t>(updatedOperations.size()));

        // 4. Find edenOperand for options if exists
        void* addrForOptions = nullptr;
        if (edenOperation->hasOptions) {
            int32_t edenOperandIndexForOptions = edenOperation->inputOperandIndexes[edenOperation->numOfInputs - 1];
            EdenOperand* operandForOptions = getEdenOperand(edenModel_, edenOperandIndexForOptions);
            if (operandForOptions->buffer == nullptr) {
                LOGE(EDEN_DRIVER, "Oops, operandForOptions->buffer is NULL! Please check it!\n");
                return BUFFER_ON_OPTION_IS_NULL;
            }
            addrForOptions = operandForOptions->buffer->addr;
        }

        // 5. Load input operand at idx into edenOperation.
//        loadAndroidModelInputToEdenOperation(model, indexNumber, androidOperation, nullptr, 0, addrForOptions);
    }

    LOGD(EDEN_DRIVER, "%s(-)\n", __func__);
    return RET_OK;
}

/**
 * @brief load data on a given srcAddr to matched target buffer which is given as an input index
 * @details This function loads data on a given srcAddr to matched target buffer which is given as an input index.
 * @param[in] srcAddr address for data to be loaded
 * @param[in] length length of data
 * @param[in] inputIdx input index on request.inputs
 * @returns return code
 */
int32_t EdenPreparedModel::loadDataOnTargetBuffer(char* srcAddr, int32_t length, int32_t inputIdx) {
    LOGD(EDEN_DRIVER, "%s(+)\n", __func__);

    void* targetAddr = nullptr;
    int32_t targetSize = 0;

    // Get android operand id used as model input
    int32_t androidOperandIdx = model.main.inputIndexes[inputIdx];

    // Which operation uses this operand id as input?

    // Case 1. GraphGen supports the model, or there is matched edenOperand. That means memcpy is enough.
    bool exist = false;
    if (isNNCModel_) {
        exist = true;
    } else {
        auto iter = mapOperandIdFromAToE_.find(androidOperandIdx);
        if (iter != mapOperandIdFromAToE_.end()) {
            exist = true;
            LOGD(EDEN_DRIVER, "inputIndexes[%d] is converted to EdenOperand, id=[%d]\n", inputIdx, iter->second);
        }
    }

    if (exist) {  // To be loaded on input buffers
        // @todo Currently, input buffer order and input indexes has same order.
        EdenBuffer* edenBufferForInputs = reinterpret_cast<EdenBuffer*>(inputAddr);
        EdenBuffer* inputBufferAddr = &(edenBufferForInputs[inputIdx]);
        LOGD(EDEN_DRIVER, "inputBufferAddr addr:%p, size=%d\n", inputBufferAddr->addr, inputBufferAddr->size);
        targetAddr = inputBufferAddr->addr;
        targetSize = inputBufferAddr->size;

        if (targetAddr == nullptr) {
            LOGD(EDEN_DRIVER, "Oops, targetAddr == nullptr, skip it!\n");
        } else if (targetSize == 0) {
            LOGD(EDEN_DRIVER, "Oops, targetSize == 0, skip it!\n");
        } else {
            LOGD(EDEN_DRIVER, "Load from %p to %p, length=%d\n", reinterpret_cast<void*>(srcAddr), targetAddr, length);
            std::memcpy(targetAddr, reinterpret_cast<void*>(srcAddr), length);
        }
    } else {  // To be loaded on a specific position
        // 1. Who is the consumer for this input operand?
        int32_t androidOperationIdx = inputConsumers_.at(inputIdx);
        const V1_3::Operation& androidOperation = model.main.operations[androidOperationIdx];

        // 2. Find index number matched to a given androidOperandIdx
        int32_t indexNumber = 0;
        for (size_t idx = 0; idx < androidOperation.inputs.size(); idx++) {
            if (static_cast<int32_t>(androidOperation.inputs[idx]) == androidOperandIdx) {
                indexNumber = idx;
                break;
            }
        }
        LOGD(EDEN_DRIVER, "androidOperandIdx=[%d] is %dth index!\n", androidOperandIdx, indexNumber);

        // 3. Find edenOperation matched to a given androidOperationIdx
        int32_t edenOperationIdx = mapOperationIdFromAToE_[androidOperationIdx];
        EdenOperation* edenOperation = getEdenOperation(edenModel_, edenOperationIdx);

        // 3.1 Keep updated operations
        updatedOperations.push_back(edenOperationIdx);
        LOGD(EDEN_DRIVER, "push %d, numOfOperations=%d\n", edenOperationIdx, static_cast<int32_t>(updatedOperations.size()));

        // 4. Find edenOperand for options if exists
        void* addrForOptions = nullptr;
        if (edenOperation->hasOptions) {
            int32_t edenOperandIndexForOptions = edenOperation->inputOperandIndexes[edenOperation->numOfInputs - 1];
            EdenOperand* operandForOptions = getEdenOperand(edenModel_, edenOperandIndexForOptions);
            if (operandForOptions->buffer == nullptr) {
                LOGE(EDEN_DRIVER, "Oops, operandForOptions->buffer is NULL! Please check it!\n");
                return BUFFER_ON_OPTION_IS_NULL;
            }
            addrForOptions = operandForOptions->buffer->addr;
        }

        // 5. Load input operand at idx into edenOperation.
//        loadAndroidModelInputToEdenOperation(model, indexNumber, androidOperation, srcAddr, length, addrForOptions);
    }

    LOGD(EDEN_DRIVER, "%s(-)\n", __func__);
    return RET_OK;
}

/**
 * @brief show internal data
 * @details This function shows internal variables of EdenPreparedModel.
 * @returns void
 */
void EdenPreparedModel::show() {
    LOGD(EDEN_DRIVER, "modelId:%u\n", modelId);
    LOGD(EDEN_DRIVER, "inputNumOfBuffers:%d\n", inputNumOfBuffers);
    if (inputAddr != nullptr && outputAddr != nullptr) {
        for (int32_t idx = 0; idx < inputNumOfBuffers; idx++) {
            EdenBuffer* inputBufferAddr = reinterpret_cast<EdenBuffer*>(inputAddr) + idx;  // In fact, inputAddr is EdenBuffer
            LOGD(EDEN_DRIVER, "inputBufferAddr[%d]->addr:%p\n", idx, inputBufferAddr->addr);
            LOGD(EDEN_DRIVER, "inputBufferAddr[%d]->size:%d\n", idx, inputBufferAddr->size);
        }
        LOGD(EDEN_DRIVER, "outputNumOfBuffers:%d\n", outputNumOfBuffers);
        for (int32_t idx = 0; idx < outputNumOfBuffers; idx++) {
            EdenBuffer* outputBufferAddr = reinterpret_cast<EdenBuffer*>(outputAddr) + idx;  // In fact, outputAddr is EdenBuffer
            LOGD(EDEN_DRIVER, "outputBufferAddr[%d]->addr:%p\n", idx, outputBufferAddr->addr);
            LOGD(EDEN_DRIVER, "outputBufferAddr[%d]->size:%d\n", idx, outputBufferAddr->size);
        }
        LOGD(EDEN_DRIVER, "vecMappedAddr and vecMappedSize...\n");
        for (size_t idx = 0; idx < vecMappedAddr_.size(); idx++) {
            char* mappedAddr = vecMappedAddr_[idx];
            int32_t mappedSize = vecMappedSize_[idx];
            LOGD(EDEN_DRIVER, "mappedAddr:%p\n", mappedAddr);
            LOGD(EDEN_DRIVER, "mappedSize:%d\n", mappedSize);
        }
    } else {
        LOGE(EDEN_DRIVER, "inputAddr or outputAddr is nullptr!\n");
    }
    LOGD(EDEN_DRIVER, "vecMappedAddr and vecMappedSize...Done!\n");
}

bool EdenPreparedModel::initializeManagedBuffer(uint32_t token) const {
    return nnAgent_->initializeManagedBuffer(token);
}

bool EdenPreparedModel::IsInvalidParams() {

    for (const V1_3::Operation &operation : model.main.operations) {
        int32_t opType = static_cast<int32_t>(operation.type);
        // Check if first dimension of input0 is not 1 for depthwise_conv2D
        if (opType == ANEURALNETWORKS_DEPTHWISE_CONV_2D &&
                    (model.main.operands[operation.inputs[1]].dimensions[0] != 1)) {
            return true;
        }

        if (opType == ANEURALNETWORKS_STRIDED_SLICE) {
            const uint32_t axis_mask_offset = model.main.operands[operation.inputs[6]].location.offset;
            const int32_t *axis_mask = (int32_t*)(model.operandValues.data() + axis_mask_offset);

            const uint32_t begin_offset = model.main.operands[operation.inputs[1]].location.offset;
            const int32_t *begin  = (int32_t*)(model.operandValues.data() + begin_offset);

            const uint32_t end_offset = model.main.operands[operation.inputs[2]].location.offset;
            const int32_t *end  = (int32_t*)(model.operandValues.data() + end_offset);

            const uint32_t strides_offset = model.main.operands[operation.inputs[3]].location.offset;
            const int32_t *strides  = (int32_t*)(model.operandValues.data() + strides_offset);

            uint32_t outputDim = (end[0] - begin[0])/strides[0];

            // This is hack to pass VTS tests.If shrink_axis_mask is not zero, then no negative strides
            // are allowed and output dimensions should be 1.
            if (axis_mask[0] && ((strides[0] < 0) || (outputDim != 1))) {
                return  true;
            }
        }
    }
    return false;
}
}  // namespace eden_driver
}  // namespace nn
}  // namespace android

