/*
 * Copyright (C) 2021 Samsung Electronics Co. LTD
 *
 * This software is proprietary of Samsung Electronics.
 * No part of this software, either material or conceptual may be copied or distributed, transmitted,
 * transcribed, stored in a retrieval system or translated into any human or computer language in any form by any means,
 * electronic, mechanical, manual or otherwise, or disclosed
 * to third parties without the express written permission of Samsung Electronics.
 */

/**
 * @file    EnnPreparedModel.cpp
 * @brief   This is EnnPreparedModel class file.
 * @details This header implements IPreparedModel interface.
 * @author  nihar.desai (nihar.desai@samsung.com)
            shashank.r (shashank.r@samsung.com)
            ankit.goel (ankit.goel@samsung.com)
 */

#include <iostream>
#include <sys/mman.h>  // munmap
#include <nnapi/Validation.h>
#include <variant>
#include <string.h>
#include "log.h"

#include "EnnPreparedModel.h"
#include "EnnBurst.h"
#include "EnnExecution.h"
#include "NNAgent.h"               // NNAgent
#include "ModelUtils.h"   // loadAndroidModelInputToEnnOperation

#ifdef LOG_TAG
#undef LOG_TAG
#endif
#define LOG_TAG "EnnDriver::EnnPreparedModel"

using namespace ::android::nn;

namespace android {
namespace nn {
namespace enn_driver {

/**
 * @brief EnnPreparedModel constructor
 * @details This function keeps all related information for a given model internally.
 * @param[in] nnAgent instance of NNAgent
 * @param[in] model Android NN Model
 * @param[in] EnnmodelId unique model id generated by Enn Framework
 * @param[in] HwType preferred hardware for execution
 * @param[in] NNCBuf NNCBuffer generated by Graphgen
 * @param[in] inputAddr InputBuffer address  returned by Enn framework
 * @param[in] int32_t number of Input Buffers
 * @param[in] outputAddr OutputBuffer address  returned by Enn Framework
 * @param[in] int32_t number of output Buffers
 * @returns return code
 */
EnnPreparedModel::EnnPreparedModel(NNAgent* nnAgent,
                                     const Model& model, EnnModelId modelId,
                                     HwType hwPreference, NNCBuf nncBuffer,
                                     void* inputAddr, int32_t inputNumOfBuffers,
                                     void* outputAddr, int32_t outputNumOfBuffers):
    model(model),
    modelId(modelId),
    hwPreference(hwPreference),
    inputAddr(inputAddr), inputNumOfBuffers(inputNumOfBuffers),
    outputAddr(outputAddr), outputNumOfBuffers(outputNumOfBuffers),
    nnAgent_(nnAgent),
    nncBuffer_(nncBuffer) {
    LOGD(ENN_DRIVER, "%s(+)\n", __func__);
    LOGD(ENN_DRIVER, "modelId: (0x%" PRIX64"), inputAddr: %p, inputNumOfBuffers: %d, outputAddr: %p, outputNumOfBuffers: %d is created!\n",
                       modelId, inputAddr, inputNumOfBuffers, outputAddr, outputNumOfBuffers);


    needInputBuffers_ = (inputAddr == nullptr ? true : false);
    needOutputBuffers_ = (outputAddr == nullptr ? true : false);

    LOGD(ENN_DRIVER, "%s(-)\n", __func__);
}

/**
 * @brief EnnPreparedModel destructor
 * @details This function releases all related information for a given model internally.
 * @returns
 */
EnnPreparedModel::~EnnPreparedModel() {
    LOGD(ENN_DRIVER, "%s(+)\n", __func__);

    if (nnAgent_) {
        nnAgent_->closeModel(modelId, nncBuffer_, inputAddr);
    }
    LOGD(ENN_DRIVER, "%s(-)\n", __func__);
}

/**
 * @brief executea model corrosponding to  EnnPreparedModel
 * @details
 * @param[in] Request Execution request with input output information
 * @param[in] MeasureTiming Measure execution Time
 * @param[in] OptionalTimePoint
 * @param[in] OptionalDuration
 * @return   Pair of OutputShape and execution Timing information
 */
ExecutionResult<std::pair<std::vector<OutputShape>, Timing>> EnnPreparedModel::execute(const Request& request,
                                        MeasureTiming measure,
                                        const OptionalTimePoint& deadline,
                                        const OptionalDuration& loopTimeoutDuration,
					const std::vector<nn::TokenValuePair>& hints,
                                        const std::vector<nn::ExtensionNameAndPrefix>& extensionNameToPrefix) const  {

     LOGD(ENN_DRIVER, "%s(+)\n", __func__);

     //Validate
    const auto result = validateRequestForModel(request, this->model);
    if (!result.ok()) {
        return NN_ERROR( ErrorStatus::INVALID_ARGUMENT);
    }
    if(!verifyDimension(request, this->model)) {
       return NN_ERROR( ErrorStatus::INVALID_ARGUMENT);
    }
#ifdef NNDRIVER_DEBUG
    show();
#endif
    // Execute
    std::vector<OutputShape> outputshape;
    Timing timing;
    int32_t ret = nnAgent_->executeSynchronously(this,request,measure,outputshape,timing);
    LOGD(ENN_DRIVER, "%s(-)\n", __func__);

    if (ret != RET_OK) {
        if (ret == INVALID_PARAMS && ret != OUTPUT_FULLY_NOT_SPECIFIED) {
            return NN_ERROR(ErrorStatus::INVALID_ARGUMENT);
        }
        return NN_ERROR(ErrorStatus::GENERAL_FAILURE);
    }
    return std::make_pair(outputshape,timing);
}

GeneralResult<SharedBurst> EnnPreparedModel::configureExecutionBurst() const {

   LOGD(ENN_DRIVER, "%s(+)\n", __func__);
   return std::make_shared<const EnnBurst>(shared_from_this());
}

GeneralResult<std::pair<SyncFence, ExecuteFencedInfoCallback>> EnnPreparedModel::executeFenced(const Request& request,
                                              const std::vector<SyncFence>& waitFor,
                                              MeasureTiming measure,
                                              const OptionalTimePoint& /*deadline*/,
                                              const OptionalDuration& /*loopTimeoutDuration*/,
                                              const OptionalDuration& /*duration*/,
					      const std::vector<nn::TokenValuePair>& hints,
                                              const std::vector<nn::ExtensionNameAndPrefix>& extensionNameToPrefix) const {
    LOGD(ENN_DRIVER, "%s(+)\n", __func__);

    std::chrono::steady_clock::time_point driverStart, driverEnd, deviceStart, deviceEnd, driverStartAfterFence;
    if (measure == MeasureTiming::YES) driverStart = std::chrono::steady_clock::now();

    const auto result = validateRequestForModel(request, this->model);
    if (!result.ok()) {
       return NN_ERROR( ErrorStatus::INVALID_ARGUMENT);
    }
    if(!verifyDimension(request, this->model)) {
       return NN_ERROR( ErrorStatus::INVALID_ARGUMENT);
    }
    // Wait for the dependent events to signal
    for (const auto& syncFence : waitFor) {
       if (!syncFence.getSharedHandle()) {
           return NN_ERROR(ErrorStatus::INVALID_ARGUMENT);
        }

        if (syncFence.syncWait({}) != SyncFence::FenceState::SIGNALED) {
            return NN_ERROR(ErrorStatus::GENERAL_FAILURE) << "syncWait failed";
        }
    }

    if (measure == MeasureTiming::YES) driverStartAfterFence = std::chrono::steady_clock::now();
    // Execute
    std::vector<OutputShape> outputshape;
    Timing timing;

    if (measure == MeasureTiming::YES) deviceStart = std::chrono::steady_clock::now();
    //Removing timimg from execute call and mesure outside. Nihar ?
    int32_t ret = nnAgent_->executeSynchronously(this,request,measure,outputshape,timing);
    if (ret != RET_OK) {
       if (ret == INVALID_PARAMS) {
          return NN_ERROR(ErrorStatus::INVALID_ARGUMENT);
       }
      return NN_ERROR(ErrorStatus::GENERAL_FAILURE);
    }
    if (measure == MeasureTiming::YES) deviceEnd = std::chrono::steady_clock::now();

    Timing timingSinceLaunch = {};
    Timing timingAfterFence = {};
    if (measure == MeasureTiming::YES) {
        driverEnd = std::chrono::steady_clock::now();
        timingSinceLaunch = {.timeOnDevice = deviceEnd - deviceStart,
                             .timeInDriver = driverEnd - driverStart};
        timingAfterFence = {.timeOnDevice = deviceEnd - deviceStart,
                            .timeInDriver = driverEnd - driverStartAfterFence};
    }

#if 0
    //Nihar : check if this is needed for Memory Domain
    for (const auto& output : request.outputs) {
        const uint32_t poolIndex = output.location.poolIndex;
	const auto& pool = request.pools[poolIndex];
	if(std::holds_alternative<Request::MemoryDomainToken>(pool)) {
	    bufferWrappers[poolIndex]->setInitialized(true);
	}
     }
#endif
    ExecuteFencedInfoCallback fencedExecutionCallback = [timingSinceLaunch, timingAfterFence]() {
        return std::make_pair(timingSinceLaunch, timingAfterFence);
    };

    LOGD(ENN_DRIVER, "%s(-)\n", __func__);
    return std::make_pair(SyncFence::createAsSignaled(), std::move(fencedExecutionCallback));
}

std::any EnnPreparedModel::getUnderlyingResource() const {
     return model;
}

GeneralResult<SharedExecution> EnnPreparedModel::createReusableExecution(
        const Request& request, MeasureTiming measure,
        const OptionalDuration& loopTimeoutDuration,
        const std::vector<nn::TokenValuePair>& hints,
        const std::vector<nn::ExtensionNameAndPrefix>& extensionNameToPrefix) const {
            return make_shared<EnnExecution>(shared_from_this(), request, measure,
                                             loopTimeoutDuration);
}

/**
 * @brief load input data on request and copy them to EnnBuffers for inputs
 * @details This function loads a buffers on request and copy them to EnnBuffers for inputs.
 *          EnnBuffers should be allocated before.
 *          If inputs[idx].hasNoValue==1, it loads 1)default values or 2)set size to 0.
 * @param[in] request Request
 * @returns return code
 */
int32_t EnnPreparedModel::loadInputData(const Request& request, BufferInfoOnExecute& bufInfoOnExecute) const {
    LOGD(ENN_DRIVER, "%s(+)\n", __func__);

    int32_t  *inputArray;
    int32_t   inputArrayIdx = 0;
    inputArray = new int32_t[model.main.operands.size()];
    for ( int32_t in = 0; in < model.main.operations.size(); in++) {
        const Operation&  androidOperation = model.main.operations[in];
        for (int32_t k = 0; k < androidOperation.inputs.size();k++) {
            auto inputId = androidOperation.inputs[k];
            if (model.main.operands[inputId].lifetime == Operand::LifeTime::SUBGRAPH_INPUT) {
                inputArray[inputArrayIdx++] = inputId;
            }
        }
    }

    const std::vector<Request::Argument>& inputs = request.inputs;
    LOGD(ENN_DRIVER, "No of input requests = %d\n", inputs.size());
    for (int32_t idx = 0; idx < inputs.size(); idx++) {
        int32_t it = idx;

        LOGD(ENN_DRIVER, "InputArray[%d]= %d\n", idx, inputArray[idx]);
        auto itr = find(model.main.inputIndexes.begin(), model.main.inputIndexes.end(), inputArray[idx]);
        if (itr != model.main.inputIndexes.end()) {
            it = itr - model.main.inputIndexes.begin();
        }
        const Request::Argument &inputArgs = inputs[it];

	if (inputArgs.lifetime == Request::Argument::LifeTime::NO_VALUE) {
            LOGD(ENN_DRIVER, "Input[%d] has no value\n", idx);
            EnnBufferPtr* ennBufferForInputs = reinterpret_cast<EnnBufferPtr *>(inputAddr);
            EnnBuffer *inputBufferAddr = ennBufferForInputs[idx];
            if (inputBufferAddr == nullptr) {
                LOGD(ENN_DRIVER, "Oops, inputBufferAddr is null!!, skip it!\n");
                continue;
            }
            auto &empty_buf = inputBufferAddr;
            reinterpret_cast<unsigned char *>(empty_buf->va)[0] = 0xFE;
            reinterpret_cast<unsigned char *>(empty_buf->va)[1] = 0xAB;
            LOGD(ENN_DRIVER, "Set Empty Input if length is 0\n");
            continue;
	}
        // Get virtual address of input data at #idx
        int32_t poolIndex = inputArgs.location.poolIndex;
        int32_t offset = inputArgs.location.offset;
        int32_t length = inputArgs.location.length;

        LOGD(ENN_DRIVER, "inputIndex= [%zu],it = [%d], poolIndex = [%d], offset = [%d], length = [%d]\n", idx, it, poolIndex, offset, length);
        if (const auto *sharedMem = std::get_if<SharedMemory>(&request.pools[poolIndex])) {
            char* virtAddr = nullptr;
            uint32_t msize;
            int32_t ret = bufInfoOnExecute.loadSharedMem(*sharedMem, true, virtAddr, msize);
            if (ret != RET_OK) {
                LOGE(ENN_DRIVER, "%s(-) Fail on getVirtualAddressOnPool!\n", __func__);
                delete[] inputArray;
                return ret;
            }

            ret = loadDataOnTargetBuffer(virtAddr + offset, length, idx);
            if (ret != RET_OK) {
                LOGE(ENN_DRIVER, "%s(-) Fail on loadDataOnTargetBuffer!\n", __func__);
                delete[] inputArray;
                return ret;
            }
        }
    }
    delete[] inputArray;
    LOGD(ENN_DRIVER, "%s(-)\n", __func__);
    return 0;
}

/**
 * @brief load data on a given srcAddr to matched target buffer which is given as an input index
 * @details This function loads data on a given srcAddr to matched target buffer which is given as an input index.
 * @param[in] srcAddr address for data to be loaded
 * @param[in] length length of data
 * @param[in] inputIdx input index on request.inputs
 * @returns return code
 */
int32_t EnnPreparedModel::loadDataOnTargetBuffer(char* srcAddr, int32_t length, int32_t inputIdx) const {
    LOGD(ENN_DRIVER, "%s(+)\n", __func__);

    void* targetAddr = nullptr;
    int32_t targetSize = 0;

    // Get android operand id used as model input
    int32_t androidOperandIdx = model.main.inputIndexes[inputIdx];

    // Which operation uses this operand id as input?


     // To be loaded on input buffers
     // @todo Currently, input buffer order and input indexes has same order.
    EnnBufferPtr* ennBufferForInputs = reinterpret_cast<EnnBufferPtr *>(inputAddr);
    EnnBuffer *inputBufferAddr = ennBufferForInputs[inputIdx];
    if (inputBufferAddr == nullptr) {
        LOGD(ENN_DRIVER, "Oops, inputBufferAddr is null!!, skip it!\n");
        return RET_OK;
    }
    LOGD(ENN_DRIVER, "inputBufferAddr addr:%p, size=%d\n", inputBufferAddr->va, inputBufferAddr->size);
    targetAddr = inputBufferAddr->va;
    targetSize = inputBufferAddr->size;

    if (targetAddr == nullptr) {
        LOGD(ENN_DRIVER, "Oops, targetAddr == nullptr, skip it!\n");
    } else if (targetSize == 0) {
        LOGD(ENN_DRIVER, "Oops, targetSize == 0, skip it!\n");
    } else if (targetSize != length) {
        LOGD(ENN_DRIVER, "Oops, Source and TargetSize not matching!!\n");
    } else {
        LOGD(ENN_DRIVER, "Load from %p to %p, size=%d\n", reinterpret_cast<void*>(srcAddr), targetAddr, length);
        std::memcpy(targetAddr, reinterpret_cast<const void*>(srcAddr), length);
    }
#ifdef NNDRIVER_DEBUG
    //For Debug
    LOGD(ENN_DRIVER, "Dump addr=[%p], size=[%d] on stdio...\n", targetAddr, targetSize);
    unsigned char* chPtr = reinterpret_cast<unsigned char*>(targetAddr);
    for (int32_t pidx = 0; pidx < targetSize; pidx++) {
        LOGD(ENN_DRIVER, "%x \n", static_cast<int32_t>(chPtr[pidx]));
    }
    LOGD(ENN_DRIVER, "Dump addr=[%p], size=[%d] on stdio...Done!\n", targetAddr, length);
#endif
    LOGD(ENN_DRIVER, "%s(-)\n", __func__);
    return RET_OK;
}

/**
 * @brief show internal data
 * @details This function shows internal variables of EnnPreparedModel.
 * @returns void
 */
#ifdef NNDRIVER_DEBUG
void EnnPreparedModel::show() const {
    LOGD(ENN_DRIVER, "modelId:%u\n", modelId);
    LOGD(ENN_DRIVER, "inputNumOfBuffers:%d\n", inputNumOfBuffers);
    if (inputAddr != nullptr && outputAddr != nullptr) {
        for (int32_t idx = 0; idx < inputNumOfBuffers; idx++) {
            EnnBufferPtr *inputBufferAddr = reinterpret_cast<EnnBufferPtr*>(inputAddr) ;  // In fact, inputAddr is EnnBuffer
            LOGD(ENN_DRIVER, "inputBufferAddr[%d]->addr:%p\n", idx, inputBufferAddr[idx]->va);
            LOGD(ENN_DRIVER, "inputBufferAddr[%d]->size:%d\n", idx, inputBufferAddr[idx]->size);
        }
        LOGD(ENN_DRIVER, "outputNumOfBuffers:%d\n", outputNumOfBuffers);
        for (int32_t idx = 0; idx < outputNumOfBuffers; idx++) {
            EnnBufferPtr* outputBufferAddr = reinterpret_cast<EnnBufferPtr*>(outputAddr);  // In fact, outputAddr is EnnBuffer
            LOGD(ENN_DRIVER, "outputBufferAddr[%d]->addr:%p\n", idx, outputBufferAddr[idx]->va);
            LOGD(ENN_DRIVER, "outputBufferAddr[%d]->size:%d\n", idx, outputBufferAddr[idx]->size);
        }
    }
    LOGD(ENN_DRIVER, "vecMappedAddr and vecMappedSize...Done!\n");
}
#endif

bool EnnPreparedModel::initializeManagedBuffer(Request::MemoryDomainToken token) const {
    return nnAgent_->initializeManagedBuffer(token);
}

bool EnnPreparedModel::IsInvalidParams() const {

    for (const Operation &operation : model.main.operations) {
        int32_t opType = static_cast<int32_t>(operation.type);
        // Check if first dimension of input0 is not 1 for depthwise_conv2D
        if (opType == ANEURALNETWORKS_DEPTHWISE_CONV_2D &&
                    (model.main.operands[operation.inputs[1]].dimensions[0] != 1)) {
            return true;
        }
#if 0
        if (opType == ANEURALNETWORKS_STRIDED_SLICE) {
            const uint32_t axis_mask_offset = model.main.operands[operation.inputs[6]].location.offset;
            const int32_t *axis_mask = (int32_t*)(model.operandValues.data() + axis_mask_offset);

            const uint32_t begin_offset = model.main.operands[operation.inputs[1]].location.offset;
            const int32_t *begin  = (int32_t*)(model.operandValues.data() + begin_offset);

            const uint32_t end_offset = model.main.operands[operation.inputs[2]].location.offset;
            const int32_t *end  = (int32_t*)(model.operandValues.data() + end_offset);

            const uint32_t strides_offset = model.main.operands[operation.inputs[3]].location.offset;
            const int32_t *strides  = (int32_t*)(model.operandValues.data() + strides_offset);

            uint32_t outputDim = (end[0] - begin[0])/strides[0];

            // This is hack to pass VTS tests.If shrink_axis_mask is not zero, then no negative strides
            // are allowed and output dimensions should be 1.
            if (axis_mask[0] && ((strides[0] < 0) || (outputDim != 1))) {
                return  true;
            }
        }
#endif
    }

    return false;
}
}  // namespace enn_driver
}  // namespace nn
}  // namespace android

